// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCUcgAhT__KeRfRm8fHpCKcI0E3mHKmHgE',
    appId: '1:573043562926:web:19761678496603d8bcd03f',
    messagingSenderId: '573043562926',
    projectId: 'nightview-d5406',
    authDomain: 'nightview-d5406.firebaseapp.com',
    storageBucket: 'nightview-d5406.appspot.com',
    measurementId: 'G-8ZS8W69Y57',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBqn2Sk8IfutCZY88-MgjFY5r9VUsBybyU',
    appId: '1:573043562926:android:73aeb3f31d35aa23bcd03f',
    messagingSenderId: '573043562926',
    projectId: 'nightview-d5406',
    storageBucket: 'nightview-d5406.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD3u5Zv6CaqBFOpfQdMH_THnmMLcQ5F180',
    appId: '1:573043562926:ios:312d4908ac92caffbcd03f',
    messagingSenderId: '573043562926',
    projectId: 'nightview-d5406',
    storageBucket: 'nightview-d5406.appspot.com',
    iosClientId: '573043562926-rtsgvlrmoe1lo7qt8u59lerq5qvo03bp.apps.googleusercontent.com',
    iosBundleId: 'com.nightview.nightview',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD3u5Zv6CaqBFOpfQdMH_THnmMLcQ5F180',
    appId: '1:573043562926:ios:312d4908ac92caffbcd03f',
    messagingSenderId: '573043562926',
    projectId: 'nightview-d5406',
    storageBucket: 'nightview-d5406.appspot.com',
    iosClientId: '573043562926-rtsgvlrmoe1lo7qt8u59lerq5qvo03bp.apps.googleusercontent.com',
    iosBundleId: 'com.nightview.nightview',
  );
}
